server:
  port: 8018

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: twg
    password: 123456
netty:
  #监听websocket连接的端口
  port: 11111
  #此处要用电脑的ip,不然手机访问会出现问题
  ws: ws://127.0.0.1:${netty.port}/ws
